<?php

namespace ContainerQmXfR90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FYYvm8hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FYYvm8h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FYYvm8h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'memberRepository' => ['privates', 'App\\Repository\\MemberRepository', 'getMemberRepositoryService', true],
            'paragraphRepository' => ['privates', 'App\\Repository\\ParagraphRepository', 'getParagraphRepositoryService', true],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'fileUploader' => 'App\\Service\\FileUploader',
            'memberRepository' => 'App\\Repository\\MemberRepository',
            'paragraphRepository' => 'App\\Repository\\ParagraphRepository',
        ]);
    }
}
