<?php

namespace ContainerQmXfR90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PQvktTxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pQvktTx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pQvktTx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'caseStudyRepository' => ['privates', 'App\\Repository\\CaseStudyRepository', 'getCaseStudyRepositoryService', true],
        ], [
            'caseStudyRepository' => 'App\\Repository\\CaseStudyRepository',
        ]);
    }
}
