<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQmXfR90\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQmXfR90/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQmXfR90.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQmXfR90\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQmXfR90\App_KernelDevDebugContainer([
    'container.build_hash' => 'QmXfR90',
    'container.build_id' => 'be4d6d4b',
    'container.build_time' => 1691479463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQmXfR90');
