<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_users_get' => [[], ['_controller' => 'App\\Controller\\Api\\UserController::index'], [], [['text', '/api/users']], [], [], []],
    'api_users_post' => [[], ['_controller' => 'App\\Controller\\Api\\UserController::create'], [], [['text', '/api/users']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_api_admin_getalladmin' => [[], ['_controller' => 'App\\Controller\\Api\\AdminController::getAllAdmin'], [], [['text', '/api/admin/get_all_admin']], [], [], []],
    'app_api_article_getarticles' => [[], ['_controller' => 'App\\Controller\\Api\\ArticleController::getArticles'], [], [['text', '/api/article/']], [], [], []],
    'app_api_article_newarticle' => [[], ['_controller' => 'App\\Controller\\Api\\ArticleController::newArticle'], [], [['text', '/api/article/new']], [], [], []],
    'app_api_article_getparagraphsbyarticle' => [['id'], ['_controller' => 'App\\Controller\\Api\\ArticleController::getParagraphsByArticle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/article/getArticle']], [], [], []],
    'app_case_study_index' => [[], ['_controller' => 'App\\Controller\\Api\\CaseStudyController::getAll'], [], [['text', '/api/case_study/']], [], [], []],
    'app_api_category_getallcategory' => [[], ['_controller' => 'App\\Controller\\Api\\CategoryController::getAllCategory'], [], [['text', '/api/category/']], [], [], []],
    'app_api_login_login' => [[], ['_controller' => 'App\\Controller\\Api\\LoginController::login'], [], [['text', '/api/login']], [], [], []],
    'app_api_main_getconferencelink' => [[], ['_controller' => 'App\\Controller\\Api\\MainController::getConferenceLink'], [], [['text', '/getConferenceSubscribeLink']], [], [], []],
    'app_api_main_getcoffeeinfo' => [[], ['_controller' => 'App\\Controller\\Api\\MainController::getCoffeeInfo'], [], [['text', '/getCoffeeSubscribeInfo']], [], [], []],
    'app_api_member_getstaff' => [[], ['_controller' => 'App\\Controller\\Api\\MemberController::getStaff'], [], [['text', '/api/members/staff']], [], [], []],
    'app_api_member_getmentors' => [[], ['_controller' => 'App\\Controller\\Api\\MemberController::getMentors'], [], [['text', '/api/members/mentors']], [], [], []],
    'app_api_member_getwitnesses' => [[], ['_controller' => 'App\\Controller\\Api\\MemberController::getWitnesses'], [], [['text', '/api/members/witnesses']], [], [], []],
    'app_api_role_index' => [[], ['_controller' => 'App\\Controller\\Api\\RoleController::index'], [], [['text', '/api/role/']], [], [], []],
];
